# [base_dir = "{dir}"]
# [go = "{cmd}"]
# [new = "{cmd}"]
# [open = "{cmd}"]
#
# [<{platform}|[{platform}.]{shell}>]
# [base_dir = "{dir}"]
# [go = "{cmd}"]
# [new = "{cmd}"]
# [open = "{cmd}"]
#
# [[{platform}.][{shell}.]{language}]
# # {base_dir}/name/proj_name
# [base_dir = "{dir}"]
# # base_dir/{name}/proj_name
# [name = "{dir_name}"]
# # command to invoke when running proj go {...}
# [go = "{cmd}"]
# # command to invoke when running proj new {...}
# [new = "{cmd}"]
# # command to invoke when running proj open {...}
# [open = "{cmd}"]

# The representation of the toml is as follows:
# {[system]: {[shell]: {[language]: {...}, [language]: {...}}, [language]: {...}}, [shell]: {...}, [language]: {...}}
# if you are on linux using bash (sh) and have specified python as the project language, the lookup is as follows:
# look in the table root for 'linux'. If found, look for 'sh'. finally, look for 'python'.
# if any step fails, look in the parent table for that key, traversing upwards until the root is searched.
# if that key is still not found, go back to previous location and start searching with the next key.
# for leaf values, only [base_dir, new, go, open] will drop their language and search in the root table for their values.

base_dir = "$HOME/Documents/"
new = "echo \"new %{path}\""

[rust]
go = "cd \"%{path}\""
open = "if [ -e src/main.rs ]; then nvim src/main.rs; else nvim src/lib.rs; fi"

[python]
vars.env_name = "env"
new = """mkdir %{path} && python3 -m venv %{env_name}"""
go = "cd %{dir} && source %{env_name}/bin/activate"

[ps1.python]
new = "New-Item -d %{dir} && python3 -m venv %{env_name}"
